### ISSUE TITLE
build error!!!

### ISSUE THREAD

**Issue by dongjiang1989** [lfai/lfai-landscape#95]
retrying... { TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r641577
        at onTimeout (/var/lib/docker/dongjiang/source/lfdl-landscape/node_modules/interactive-landscape/node_modules/puppeteer/lib/Launcher.js:353:14)
        at Timeout.callback (/var/lib/docker/dongjiang/source/lfdl-landscape/node_modules/interactive-landscape/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }

**Comment by dankohn** [comment]
Please open an issue on https://github.com/cncf/landscapeapp describing your problem in more detail.
